version: "3.0"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - api.env
    networks:
      - public
#     - private
    restart: on-failure
    volumes:
      - ./:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - mysql.env
    networks:
      - public
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  public:
    driver: bridge
#  private:
volumes:
  mysql_data: 
  # dummy

      
